export default [
  { name: "Bloomsbury", path: "/assets/img/publishers/bloomsbury.png" },
  { name: "Countryman Press", path: "/assets/img/publishers/countryman.png" },
  { name: "Crown Press", path: "/assets/img/publishers/crown.png" },
  { name: "Hachette Books", path: "/assets/img/publishers/hachette.png" },
  { name: "HarperCollins", path: "/assets/img/publishers/harpercollins.png" },
  { name: "Harvard Business Review", path: "/assets/img/publishers/hbr.png" },
  { name: "O'Reilly", path: "/assets/img/publishers/oreilly.png" },
  { name: "OU Press", path: "/assets/img/publishers/ou.png" },
  { name: "Penguin Random House", path: "/assets/img/publishers/penguin.png" },
  { name: "Post Hill Press", path: "/assets/img/publishers/posthill.png" },
  { name: "Rodale", path: "/assets/img/publishers/rodale.png" },
  { name: "Schiffer Publishing", path: "/assets/img/publishers/schiffer.png" },
  { name: "Seal Press", path: "/assets/img/publishers/seal.png" },
  { name: "Simon & Schuster", path: "/assets/img/publishers/simon.png" },
  { name: "Sourcebooks", path: "/assets/img/publishers/sourcebooks.png" },
  { name: "Spiegel and Grau", path: "/assets/img/publishers/spiegel.png" },
  { name: "St. Martin's Press", path: "/assets/img/publishers/stmartin.png" },
];
